### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by winwisely99** [ncruces/zenity#1]
This looks like a really clean bring up of Native desktop stuff that lots of project needs.

Any plans for Printing.

Saw this: github.com/alexbrainman/printer
- ONYL works on windows

**Comment by ncruces** [comment]
Printing is an interesting case.

The Windows printing dialog would be easy to wrap, but all it does is show a dialog. Which begs the question, what do you want to print and how? There's also no direct equivalent in either Zenity (Linux) or AppleScript (macOS).

I think this is would make more sense in a dedicated printing library, something that is able to print images/PDFs/HTMLs.

**Comment by ncruces** [comment]
Feel free to reopen if you have further insights into printing UIs.

**Comment by gedw99** [comment]
I am building apps in golang.

In the app i want to allow users to print PDF's. the app is able to output PDFs.

SO i am wanting help / advice about bringup up the print dialogue and then as the user makes selections like like page size, my app responds with a image ( that is a prox for the actual PDF) to be shown in the print preview.

there are a few other print and print preview interactions i imagine, like changing the orientation, choosing between a colour and black and white printer.

I have a basic test harness here: https://github.com/gedw99/gio-print/blob/main/example/tree/tree.png
and docs about how i think it could work here: https://github.com/gedw99/gio-print/tree/main/docs

**Comment by ncruces** [comment]
Sorry, I don't think I can be of much help.

On Windows, I don't think the common dialog APIs support your use case very well (incl. print preview). In any event, your docs show you're in the right track there.

On Mac/Linux, as I said above, the stuff I currently use has nothing for print.

My desktop UIs are basically web based (I launch Chrome in app mode). So for printing I just use the browser, with a printing CSS.

**Comment by gedw99** [comment]
No worries
