### ISSUE TITLE
WM_CLASS on Linux Xorg

### ISSUE THREAD

**Issue by xEricL** [ncruces/zenity#107]
I am using Zenity to create a progress bar for when my application is starting. In order to get the window icon working properly on Xorg Linux systems, I need to modify the WM_Class of the progress bar window. This usually comes from the title of the window. Currently, the WM_Class is set to `zenity`. Is there any way to change that?

I know I can just change the `StartupWMClass` attribute defined in my .desktop file, but changing that to "zenity" seems like a hacky solution and it might affect the icon of other applications that might be using this library.

**Comment by xEricL** [comment]
Also, `zenity.Notify` seems to also use "zenity" as the title for the notification, even if i set the `zenity.Title()` option to something else.

![image](https://github.com/user-attachments/assets/697c2e99-f7a9-42c0-be73-d799eb08b146)

**Comment by ncruces** [comment]
To be honest, I don't know, I just run zenity.

These questions would be better asked in [zenity's repo](https://gitlab.gnome.org/GNOME/zenity).

Also, I found this in their issue tracker:
https://gitlab.gnome.org/GNOME/zenity/-/issues/83
