### ISSUE TITLE
Terminal loses focus after selecting file.

### ISSUE THREAD

**Issue by lonnywong** [ncruces/zenity#120]
1. Run `zenity --file-selection` in Windows Terminal.
2. Select a file.
3. If you press any key on the keyboard without clicking the mouse, you cannot type.

**Comment by ncruces** [comment]
See #121.

Leaving open to see if anyone can contribute a fix.

**Comment by lonnywong** [comment]
It works good with [Windows Terminal v1.21.2701.0](https://github.com/microsoft/terminal/releases/tag/v1.21.2701.0). Fixed by https://github.com/microsoft/terminal/pull/17828.
