### ISSUE TITLE
Simple usage examples

### ISSUE THREAD

**Issue by jcobhams** [ncruces/zenity#13]
Any simple usage examples would be great. 
The screenshot is good but no code example.

I could (would) create a PR to add this to the readme once I can figure it out myself.

**Comment by ncruces** [comment]
Do you mean Go examples, or `zenity` command examples?

For the first kind (Go examples), you can look at the official package documentation: https://pkg.go.dev/github.com/ncruces/zenity#pkg-examples

For the second kind (`zenity` command), the Zenity documentation it's trying to emulate should be useful (most examples should work unmodified):
https://help.gnome.org/users/zenity/stable/

**Comment by VinGarcia** [comment]
@ncruces why not just add this two links to the README file?
