### ISSUE TITLE
The class already exists

### ISSUE THREAD

**Issue by ManuCiao10** [ncruces/zenity#130]
Hello, I'm running the Zenity Entry function inside a goroutine. I'm having the following error: "The class already exists." It looks like this error only occurs on Windows.

**Comment by ManuCiao10** [comment]
otp, err := zenity.Entry("Enter OTP",
			zenity.Title("OTP"),
			zenity.OKLabel("Submit"),
			zenity.CancelLabel("Cancel"),
			zenity.EntryText(""),
		)

**Comment by ncruces** [comment]
See: #121
