### ISSUE TITLE
zenity.SelectFileSave adds a \n character

### ISSUE THREAD

**Issue by SolarLune** [ncruces/zenity#14]
Hello!

This is weird, but when I call `zenity.SelectFileSave()`, it adds a newline character at the end of the filepath returned by the function, regardless of what I type in for the filename. Here's a quick test:

```
package main

import (
	"fmt"

	"github.com/ncruces/zenity"
)

func main() {

	filename, err := zenity.SelectFileSave()

	if err != nil {
		panic(err)
	}

	fmt.Println(fmt.Sprintf("%q", filename))

}

```

And here's the output with a saved file named `test`:
`"/home/solarlune/Documents/Projects/Go/Tests/zenity/test\n"`

This is a fresh project with freshly `go get`ted zenity, Pop OS 20.10, go version 1.16.2.

**Comment by ncruces** [comment]
This was introduced in [`71541c2`](https://github.com/ncruces/zenity/commit/71541c249aec3f089764856b606b7f586eab5938#diff-90ba3cdd5f893e1f26d8af64f999f67163b5dd05881386cd029766be4a6ca395). I'll revert that change.

Thanks!

**Comment by ncruces** [comment]
Tagged as [v0.7.4](https://github.com/ncruces/zenity/releases/tag/v0.7.4).

Will do the release shortly, but it should be available through `go get`.

**Comment by SolarLune** [comment]
Fantastic. Thanks a lot for the prompt fix; really appreciate it!
