### ISSUE TITLE
FileFilter with ".xlsx" doesn't work

### ISSUE THREAD

**Issue by future-shibukawa** [ncruces/zenity#15]
Thank you for your great product. I tried the following code on Mac, that doesn't enable *.xlsx file selection.

```go
package main

import (
	"log"

	"github.com/ncruces/zenity"
)


func main() {
	path, err := zenity.SelectFile(
		zenity.Title("Select xlsx file"),
		zenity.FileFilter{
			Name: "Excel files",
			Patterns: []string{"*.xlsx"},
		},
	)
	log.Println(path, err)
}
```

I tried the following extensions, only MS office files are not acceptable.

* .xlsx: ng
* .pptx: ng
* .pdf: ok
* .png: ok
* .tar.gz: ok
* .dmg: ok

**Comment by ncruces** [comment]
This is a macOS (AppleScript) bug. It seems the first pattern cannot be a 4 letter extension, for some reason.
However, it is unlike Apple will fix this, so I added a workaround.

To show that this is a bug for Apple to fix, try this:

```
osascript -e 'choose file of type ["xls"]'
osascript -e 'choose file of type ["xlsx"]'
osascript -e 'choose file of type ["", "xlsx"]'
```

First one should work, second one should **not**, third is my workaround: specify an empty string as the first pattern.

I'll tag a new version in a bit that does this (add an empty first pattern) automatically.

**Comment by ncruces** [comment]
Version [`v0.7.7`](https://github.com/ncruces/zenity/releases/tag/v0.7.7) should fix this.
