### ISSUE TITLE
-notification show nothing in win7  git-for-windows

### ISSUE THREAD

**Issue by jackusay** [ncruces/zenity#17]
In win7 64bit / v0.7.9  / git-for-windows (in cmder):

```
./zenity.exe --notification --text "Good Morning"
```

show: nothing

---
run powershell gui in cmd:

```
powershell -Command "& {Add-Type -AssemblyName System.Windows.Forms; Add-Type -AssemblyName System.Drawing; $notify = New-Object System.Windows.Forms.NotifyIcon; $notify.Icon = [System.Drawing.SystemIcons]::Information; $notify.Visible = $true; $notify.ShowBalloonTip(0, 'Hello world', 'This is called from a batch script.', [System.Windows.Forms.ToolTipIcon]::None)}"
```

work great:
![2021-08-07 14_14_11-Cmder](https://user-images.githubusercontent.com/58719891/128590393-6c17a06b-461a-4440-8d88-30821b749f2d.jpg)

**Comment by ncruces** [comment]
That's strange. I don't have Windows 7 to repro, but I'll try to find a VM.

If you can help trace it down, it would be highly appreciated. Thanks!

**Comment by princessmortix** [comment]
Nope, doesnt work

https://user-images.githubusercontent.com/47502554/129185199-f61d0b89-4fd6-4168-9695-7f32ccef06e1.mp4

(Tested on a clean windows 7 virtual machine using the x64 binary from the releases page with Virtual Box)

**Comment by princessmortix** [comment]
Also its returns status code 0.
![errorcode](https://user-images.githubusercontent.com/47502554/129187079-f7c30e5a-7dc5-4d82-b5cb-0f60f40e01cc.png)

**Comment by ncruces** [comment]
I'm not doubting your report, I'm asking for help.

Did you try - can you try - fixing the issue?

It should be in this function: https://github.com/ncruces/zenity/blob/2fa0d652db7dbda332f5d7d2688d70ae8536a23d/notify_windows.go#L16-L57

Failing that, do you know of any Windows 7 image I can use to test this?

**Comment by princessmortix** [comment]
https://dl.bobpony.com/windows/7/en_windows_7_with_sp1_x64.iso (from https://downloadui.bobpony.com, Bob Pony's website) or https://dl.malwarewatch.org/windows/Windows%207%20(x64).iso (from https://malwarewatch.org, Endermanch's website)

**Comment by ncruces** [comment]
Please test: https://github.com/ncruces/zenity/releases/tag/v0.7.11

**Comment by princessmortix** [comment]
Sorry for the late reply

![worked](https://user-images.githubusercontent.com/47502554/129554898-c999f9ca-335f-4899-a228-4206cb06826a.png)

It worked!

**Comment by ncruces** [comment]
I have to say I'm not entirely happy with this solution, but it's Windows 7: time to move on.
I won't complicate the code further just for Windows 7 and below.
This should be good enough.
