### ISSUE TITLE
Dialog progress crashing at dlg.Complete()

### ISSUE THREAD

**Issue by princessmortix** [ncruces/zenity#18]
Using the progress bar dialog, after the dlg.Complete() function I got the following error:

```Failed to find SetWindowLongPtrW procedure in user32.dll: Could not find the specified procedure.```

On older versions it was working fine.

**Comment by ncruces** [comment]
Are you compiling for 32-bit Windows? It seems `SetWindowLongPtrW` is a `define` there, not a method exported by the DLL (see [this](https://groups.google.com/g/golang-nuts/c/pkmwc8k0DpU)). I missed this detail when perusing the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptrw).

I'll fix it when I have the opportunity.
