### ISSUE TITLE
Message Dialogs

### ISSUE THREAD

**Issue by tataDan** [ncruces/zenity#2]
Is there any way to specify the size of a message box or the position where it appears on the screen?

**Comment by ncruces** [comment]
No. Specifying the size could work in Unix (through the `zenity` command), but wouldn't on Windows (`MessageBoxW`) or macOS (`displayDialog`/`displayAlert`).

This would be implemented as an additional "Unix only" option to the message functions.

**Comment by tataDan** [comment]
Okay, Thanks for the quick response.

Is there any way to force the message dialogs to always appear on top of the application window?

**Comment by ncruces** [comment]
Currently, no. But the underlying APIs might support it. I'd need to know more to be sure, and to design a sensible cross platform way to do it, though.

So if you can provide more insight into what you're doing it will be helpful. Or maybe come up with a PR for consideration.

**Comment by ncruces** [comment]
c73af92d4ea3ca61709963e53ca0ee703891f1a7might fix some instances of dialogs appearing under other windows.

This still won't make them modal, if that was the request. That's going to be hard to do portably.
