### ISSUE TITLE
How to use zenity.Question

### ISSUE THREAD

**Issue by princessmortix** [ncruces/zenity#24]
Not sure where I should ask this but how exactly zenity.Question is used? For an example, how do I know if the user selected "Yes" ("Sim" on the screenshot)?
![Big thanks for maintaining this project](https://user-images.githubusercontent.com/47502554/147892858-001c1761-83e6-48a7-ad56-4e714f3948d3.png)

**Comment by ncruces** [comment]
`Question` returns either `nil` (for `Yes`) or `ErrCanceled` (for `No`).

I'll add that to the docs.

**Comment by princessmortix** [comment]
Thanks!
