### ISSUE TITLE
[linux] Use kdialog if zenity not available

### ISSUE THREAD

**Issue by pymq** [ncruces/zenity#25]
On some distros (like Kubuntu, openSUSE) zenity is not pre-installed and system have kdialog instead. It would be nice to transparently invoke kdialog to work out of the box on more linux systems without proper packaging or asking users to install dependencies.

Kdialog documentation: https://develop.kde.org/deploy/kdialog/

Would you be interested in such contribution?

**Comment by ncruces** [comment]
I would. But I suspect it might be hard to have a consistent feature set, no?
I'm also a bit worried about maintenance going forward.

**Comment by ncruces** [comment]
Closing due to no progress.
If anyone's interested in contributing, please reach out!
