### ISSUE TITLE
Add options dialog and entry dialog

### ISSUE THREAD

**Issue by gabyx** [ncruces/zenity#3]
It would be really nice to have  a options dialog

`zenity --list` and `zenity --entry`

See https://github.com/gen2brain/dlgs.

**Comment by ncruces** [comment]
I haven't had much time to update this.

If anyone wants to have a go, I'm willing to take pull requests.
To be successful, these should follow the guidelines set out in the [README](../#benefits), no `cgo`, `context` cancelation, etc.

[`github.com/gen2brain/dlgs`](https://github.com/gen2brain/dlgs) seems a great reference on Windows, especially since unlike other packages it is lightweight on dependencies. So thanks for that.

For a good reference for AppleScript UI see:
https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/DisplayDialogsandAlerts.html

**Comment by gabyx** [comment]
I am a bit scared, about the Windows part, because MFC is so shitty, there is no automatic a layouting which results in doing our own logic which is everything else than easy...

**Comment by ncruces** [comment]
Yes, I'm well aware that I did all the easier (not necessarily the most useful) ones. 😏

The most important to me were the file dialogs, the rest were nice to haves.

I'm halfway through an edit box, mostly for passwords, but got lost on MFC. `dlgs` seems a nice place to find code to adapt.

**Comment by gabyx** [comment]
You library is however probably does error handling etc nicer.
dlgs, has problems since it does not properly handle cancelation.

May be we can just directly take the code from dlgs. The windows common stuff at least.
And properly layout a list, and entry dialog. Because so far everything is hardcoded 🙈

**Comment by gabyx** [comment]
Optionally also replace the Error and Warning Dialogs directly with `dlgs_windwos.go`  -> this manual layout gives nicer results.

**Comment by gabyx** [comment]
Maybe instead of going down the Road of Shitty MFC:

why not just use...
https://github.com/maravento/winzenity

**Comment by ncruces** [comment]
That's "just" a build of `zenity` using [GTK for Windows](https://www.gtk.org/docs/installations/windows).

Not a big fan of the result, UI looks anything but native:
https://github.com/maravento/winzenity/issues/2#issuecomment-584833732

**Comment by gabyx** [comment]
jeah me neither... it looks ugly...

**Comment by gabyx** [comment]
I think the right way to look at is the following:

https://github.com/whtiehack/wingui

**Comment by gabyx** [comment]
checkout the examples/simple

**Comment by gabyx** [comment]
you might use: 
https://github.com/lxn/walk

**Comment by gabyx** [comment]
which is probably really the way to go to make a dialog.

**Comment by gabyx** [comment]
```go
// Copyright 2012 The Walk Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/lxn/walk"

	. "github.com/lxn/walk/declarative"
)

func main() {
	mw := &MyMainWindow{model: NewEnvModel()}

	if _, err := (MainWindow{
		AssignTo: &mw.MainWindow,
		Title:    "Walk ListBox Example",
		MinSize:  Size{240, 320},
		Size:     Size{300, 600},
		Layout:   VBox{Margins: Margins{Left: 8, Top: 8, Bottom: 8, Right: 8}},
		Children: []Widget{
			TextEdit{
				ReadOnly:           true,
				RightToLeftReading: true,
				Text:               `This is long text. This is long text. 🥶 😱 😨 😰 😥 😓 🤗 🤔 🤭 🤫 🤥 😶 😐 😑 😬 🙄 😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 🤐 🥴 🤢 🤮 🤧 😷 🤒 🤕 🤑 🤠 😈 👿 👹 👺 This is long text. This is long text.This is long text.This is long text.This is long text.This is long text.`},
			VSpacer{
				Size: 5,
			},

			RadioButtonGroupBox{
				Layout: HBox{Margins: Margins{Left: 0, Top: 0, Bottom: 0, Right: 0}},
				Buttons: []RadioButton{
					{Text: "Yes"},
					{Text: "No"},
					{Text: "Skip"},
					{Text: "Skip all"},
				},
			},
			ListBox{
				AssignTo:              &mw.lb,
				Model:                 mw.model,
				OnCurrentIndexChanged: mw.lb_CurrentIndexChanged,
				OnItemActivated:       mw.lb_ItemActivated,
			},
			VSpacer{
				Size: 5,
			},
			Composite{
				Layout: HBox{Margins: Margins{Left: 8, Top: 8, Bottom: 8, Right: 8}},
				Children: []Widget{
					PushButton{Text: "Ok"},
					PushButton{Text: "Cancel"},
				},
			},
		},
	}.Run()); err != nil {
		log.Fatal(err)
	}
}

type MyMainWindow struct {
	*walk.MainWindow
	model *EnvModel
	lb    *walk.ListBox
}

func (mw *MyMainWindow) lb_CurrentIndexChanged() {
	i := mw.lb.CurrentIndex()
	item := &mw.model.items[i]

	fmt.Println("CurrentIndex: ", i)
	fmt.Println("CurrentEnvVarName: ", item.name)
}

func (mw *MyMainWindow) lb_ItemActivated() {
	value := mw.model.items[mw.lb.CurrentIndex()].value

	walk.MsgBox(mw, "Value", value, walk.MsgBoxIconInformation)
}

type EnvItem struct {
	name  string
	value string
}

type EnvModel struct {
	walk.ListModelBase
	items []EnvItem
}

func NewEnvModel() *EnvModel {
	env := os.Environ()

	m := &EnvModel{items: make([]EnvItem, len(env))}

	for i, e := range env {
		j := strings.Index(e, "=")
		if j == 0 {
			continue
		}

		name := e[0:j]
		value := strings.Replace(e[j+1:], ";", "\r\n", -1)

		m.items[i] = EnvItem{name, value}
	}

	return m
}

func (m *EnvModel) ItemCount() int {
	return len(m.items)
}

func (m *EnvModel) Value(index int) interface{} {
	return m.items[index].name
}
```

Some example to test with `walk`.

**Comment by gabyx** [comment]
![image](https://user-images.githubusercontent.com/647437/107705130-97b8f880-6cbe-11eb-8450-3a6fcb0c2799.png)

**Comment by gabyx** [comment]
Have a look at the finished tool:

https://github.com/gabyx/githooks#dialog-tool

You can build it with

```cpp
git clone https://github.com/gabyx/githooks.git githooks
cd githooks/githooks
scripts/build.sh
bin/dialog --help
```

Enjoy (checkout `dialog --json ...` :-): If you like:
Maybe we could further develop this tool and maybe integrate the missing stuff:
- colorbar (so far I think)

**Comment by ncruces** [comment]
I'll have a look into implementing list, edit, and also password. Your Windows code might help. Glad my code helped you. Thanks!

**Comment by gabyx** [comment]
Jeah, thanks too, it helped. However, my code is based on walk, so it needs threading and main loop stuff, but how can you get proper GUI stuff without it, its a PAIN and look shit -> its called Windows :-), so at least walk provides the tools to make it proper.

My opinion: Anyway, if one doesnt want Common Control 6 on a windows server core (probably it doesn have it, dunno) then why would you want a GUI, either work in the terminal (ahh jeah windows doesnt have terminals lool) or let it be and use Linux :-).

**Comment by ncruces** [comment]
Entry dialog done.
