### ISSUE TITLE
Dialog window underneath

### ISSUE THREAD

**Issue by willmendil** [ncruces/zenity#33]
Hi, 

I ran `zenity.SelectFile(zenity.Filename(""),zenity.Directory())` in a astilectron project, and the dialog window is underneath the main window. 
Seams to be an old problem, but can't see what's the fix

**Comment by ncruces** [comment]
I imagine this is on macOS? See #28.

You can add [`zenity.Attach`](https://pkg.go.dev/github.com/ncruces/zenity#Attach) or [`zenity.WindowIcon`](https://pkg.go.dev/github.com/ncruces/zenity#WindowIcon) to try to solve your issue.

**Comment by willmendil** [comment]
actually it is on windows 11. but i found a work around with  atilectron
