### ISSUE TITLE
Using keyboard on Windows

### ISSUE THREAD

**Issue by tataDan** [ncruces/zenity#36]
When I run the following example code on Linux:

```
package main

import (
	"github.com/ncruces/zenity"
)

func main() {
	zenity.Question("Are you sure you want to proceed?",
		zenity.Title("Question"),
		zenity.QuestionIcon)
}
```
I am able to use both the mouse and the keyboard.

However, when I run the same example on Windows, I can use the mouse but not keyboard.

Is this behavior to be expected or I am doing something wrong?

**Comment by tataDan** [comment]
If I click on the dialog, then I am able to use the keyboard.  So apparently this is issue of not automatically getting focus.

**Comment by ncruces** [comment]
Are you using this in a console app? If so, focus should be automatic, I think (unless there was a regression). Can you share a [minimum reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by tataDan** [comment]
No, I am building code using a GUI framework called [wails](https://wails.io).

However, for testing purposes I also built  the console app as shown in my original post.

In Windows, when I run the console app, focus is automatically obtained, but not (interestingly) if I run it from a terminal window in Visual Studio Code, or from my GUI app.

In Linux, focus is always automatically obtained whether it is the console app run from a terminal, the console app run from the terminal in Visual Studio Code, or my GUI app.

Unless there is a simple, cross-platform solution (which I doubt), I can accept the absence of automatic focus in Windows.  Zenity has what I really need -- the "DefaultCancel" option.

Thank you

**Comment by ncruces** [comment]
Solution does not _necessarily_ need to be cross platform. There's plenty of custom Windows code in the package.
I simply asked if it was a console app as those are the tests I regularly run, and I tested this specifically (so it'd be a regression).

Also, if you're using Wails, I'm interested, actually, as I imagine others might as well.
Are you willing to experiment, i.e. making changes to `zenity`?

If so, this bit here is responsible for "finding" a "parent" window and bringing it to front:
https://github.com/ncruces/zenity/blob/e256a51c4a5c008d8281b8e08e7b31254d07ed95/util_windows.go#L30-L39

You can bootstrap this with an existing window by setting [`zenity.Attach`](https://pkg.go.dev/github.com/ncruces/zenity#Attach) with a `HWND`. Do you have one from Wails, could you try if that improves it?

If you don't call `zenity.Attach`, `setup` is called with `wnd=0`, and I try to find some window owned by your process (I may find the wrong one), or get the console window (which works for regular console, but fails with the embed VSCode terminal, known issue). If calling `zenity.Attach` works, this code might be improved.

Another thing to try would be to call [`SetFocus`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setfocus) around [here](https://github.com/ncruces/zenity/blob/e256a51c4a5c008d8281b8e08e7b31254d07ed95/msg_windows.go#L90) and maybe see if that fixes it.

**Comment by sylven32** [comment]
What brought the dialog in foreground for me was to get the current foreground window HWND and give it as the parameter to zenity.Attach. See GetForegroundWindow from user32.dll.
Not sure how reliable this is but seems to provide the expected behavior when the exe is run from msiexec and from the VSCode console as well.

**Comment by ncruces** [comment]
The problem with calling `Attach` with `GetForegroundWindow` is that it makes dialogs modal to that window, which may belong to a different process.

That's fine, of course, if that's what you want, but it's not something a library should do all by itself.

**Comment by sylven32** [comment]
Fair enough, thanks for your answer.
I'll do more tests to see if my usage of Attach really fits my needs or has any other drawbacks.

**Comment by ncruces** [comment]
Closing this, but I welcome additional contributions to the acquire focus logic.
