### ISSUE TITLE
mac: question, info -> Same icon, and the icon is a folder, which looks a bit strange

### ISSUE THREAD

**Issue by zundaren** [ncruces/zenity#60]
<img width="815" alt="image" src="https://github.com/ncruces/zenity/assets/44863479/7fca663c-e91d-417c-a734-fc9f2185ad58">

**Comment by ncruces** [comment]
That's how macOS works: the icon is the icon of the application (in this case, the application does not have an icon, so a folder is shown), with a small overlay if it's an error or warning (question and info are neither).

You can provide your own icon as an alternative, but AppleScript (which I use) does not have any other icons I could use to show.

I'm open to suggestions, though.

**Comment by zundaren** [comment]
> That's how macOS works: the icon is the icon of the application (in this case, the application does not have an icon, so a folder is shown) and an overlay if it's an error or warning (question and info are neither). There is no question mark overlay, unfortunately. You can provide your own icon as an alternative, but AppleScript (which I use) does not have any other icons/overlays I could specify.这就是macOS的工作方式：图标是应用程序的图标（在这种情况下，应用程序没有图标，因此会显示一个文件夹），如果是错误或警告，则会显示一个覆盖层（问题和信息都不是）。不幸的是，没有问号叠加。您可以提供自己的图标作为替代方案，但是AppleScript（我使用）没有我可以指定的任何其他图标/覆盖层。
> 
> I'm open to suggestions, though. 不过，我愿意接受建议。

Okay, this is a great project. Give it a thumbs up.
