### ISSUE TITLE
can you add a feature (all system): open explorer, the selected file can be located

### ISSUE THREAD

**Issue by zundaren** [ncruces/zenity#61]
1.open explorer
input: C:\Windows\appcompat

![image](https://github.com/ncruces/zenity/assets/44863479/a44332b4-1652-428d-9cd1-32a6eb7fa3b1)

2.located file
input: C:\Windows\appcompat\Programs

![image](https://github.com/ncruces/zenity/assets/44863479/0b4cfda6-4efd-481f-a7e8-c0ae8438dff7)

**Comment by ncruces** [comment]
Not that I know. Opening a folder should be “easy,” a file not so much.

This still feels a bit out of scope here…

**Comment by zundaren** [comment]
> Not that I know. Opening a folder should be “easy,” a file not so much.
> 
> This still feels a bit out of scope here…

windows: explorer.exe /e,/select,C:\Config\a.txt
mac: open -R /usr/local/a.txt
linux: nautilus -s /usr/local/a.txt
Yes, I'm using commands now, but it's not universal enough, I would like to ask if there is a relevant system api can replace the command execution.

**Comment by ncruces** [comment]
On Windows, there might be, but I really don't know. Other than that, some Windows versions might not have `explorer.exe`, but not sure there's an alternative, and it's a corner case (almost all installs will have Windows Explorer).

On macOS, that's exactly what I'd do (use `open`) thanks for the command.

On Linux depending on `nautilus`… I wouldn't. Maybe something like `xdg-open` can do what you want? That's more general.

I'm trying not to add API beyond `zenity`, but that's just personal preference.
