### ISSUE TITLE
[MacOS] Is there a way to select files and folders at the same time?

### ISSUE THREAD

**Issue by lonnywong** [ncruces/zenity#64]
`zenity.SelectFileMultiple(zenity.Directory())`  can select both files and folders on MacOS before.

Now only the folders can be selected. Don't know why.

**Comment by ncruces** [comment]
Could it? macOS has that dialog, I know, but, to my knowledge, it's not available through AppleScript, so I never implemented it.

**Comment by ncruces** [comment]
See:
https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/PromptforaFileorFolder.html
https://forum.latenightsw.com/t/method-to-allow-user-to-select-files-and-folders-in-a-single-dialog-box/

**Comment by lonnywong** [comment]
Can `go` call `NSOpenPanel` to do it?

**Comment by ncruces** [comment]
That either requires using `cgo`, which I won't do: because `cgo`, because UI stuff on macOS can only be called from the “main thread” _and_ needs some process global initialization, all of which this was designed to avoid.

The alternative is to use AppleScript to call `NSOpenPanel`. Something like this:
https://github.com/ncruces/zenity/blob/master/internal/zenutil/osascripts/date.gojs

**Comment by lonnywong** [comment]
Ok, cgo is not so good.

Can AppleScript call NSOpenPanel to implement checkbox too?

**Comment by ncruces** [comment]
Probably. The file I linked is a Go template that generates JXA (JavaScript for Automation, the JavaScript version of AppleScript). If you're curious, it's easy to hack this package to dump the generated JXA to see what's running.

AppleScript, and especially JXA, documentation is a bit hard to come by. The more complex scripts in that folder, the ones that call into Cocoa, were particularly hard to get right. There are also some hard to solve issues with capturing mouse/keyboard focus, and a showing on top of other apps.

**Comment by lonnywong** [comment]
It's nice to have. Thanks for your excellent project.
