### ISSUE TITLE
Notification style

### ISSUE THREAD

**Issue by ido2021** [ncruces/zenity#69]
@ncruces hello, i met a problem when I run zenity on Win11 OS. I get an undesired result：
![image](https://github.com/ncruces/zenity/assets/77770744/94647dc6-0d00-4752-a25a-ea55cc52ae2c)

how can i get the Windows style but not Win server core
![image](https://github.com/ncruces/zenity/assets/77770744/6a438381-9d14-4e48-bb39-3fb7773e2822)

**Comment by ncruces** [comment]
That's… interesting. I have no idea.

That means this test is failing, for some reason:
https://github.com/ncruces/zenity/blob/a6ba5a23b54e99e9b87453b6d0acbcebadeaeb27/notify_windows.go#L53

Maybe you can play around and find out?

**Comment by ido2021** [comment]
> That's… interesting. I have no idea.

Well, I don't have any ideas too. Thanks for your reply!

**Comment by ncruces** [comment]
For the [file dialog](https://github.com/ncruces/zenity/wiki/File-selection-dialog) which style do you get?

And, just to make sure, do you use the [Windows Explorer shell](https://en.wikipedia.org/wiki/Windows_shell), not an alternative like [Cairo](https://cairoshell.com/) or some other customization?

**Comment by ido2021** [comment]
the following picture is my file dialog. and I'm sure I used the Windows Explorer shell
![image](https://github.com/ncruces/zenity/assets/77770744/07646c8f-90eb-4eb1-b96f-a363f39726df)

**Comment by ncruces** [comment]
I can confirm the issue. Thanks! Not sure how to fix.
