### ISSUE TITLE
macos file-selection lose focus

### ISSUE THREAD

**Issue by jeesk** [ncruces/zenity#76]
The language of the file manager does not correspond to my system. My system is in Chinese, but when the file manager is opened, it is in English。 

![image](https://github.com/ncruces/zenity/assets/27076817/8a2333ee-ebdd-44c4-8465-c1c2cba0c7ca)

**Comment by ncruces** [comment]
On macOS we use `osascript`, the engine that drives AppleScript.

If you have any suggestions on how to improve the situation, I'll take them into account, otherwise, there isn't much I can do, sorry.

Focus issues are, unfortunately, a known issue.

**Comment by jeesk** [comment]
> On macOS we use `osascript`, the engine that drives AppleScript.
> 
> If you have any suggestions on how to improve the situation, I'll take them into account, otherwise, there isn't much I can do, sorry.
> 
> Focus issues are, unfortunately, a known issue.

ok thans

**Comment by ncruces** [comment]
Closing as there doesn't seem to be anything I can do to improve the situation.
If you have any concrete suggestion, please reopen.
