### ISSUE TITLE
unable to change the height and width of the progressDialog

### ISSUE THREAD

**Issue by kishorkumar287** [ncruces/zenity#82]
Can you please say how to change the height and width of the dialouge box in progressDialog. If i enter a large text it gets appended. I should be able to see the whole text.

![image](https://github.com/ncruces/zenity/assets/60978027/6fae548e-2e23-4cc4-bd3e-7de8d0fb686b)

**Comment by ncruces** [comment]
Which platform?

**Comment by kishorkumar287** [comment]
windows 11

**Comment by ncruces** [comment]
In general, there's no way to change the width/height of dialogs on Windows/macOS.

Not sure if it's possible to come up with something simple, but I'd like to avoid very flexible layouts. The layout code is not exactly [pretty](https://github.com/ncruces/zenity/blob/39ff6de6ef40ead5a2fed7bca2b8328e49a0f437/progress_windows.go#L214) as it is.

**Comment by ncruces** [comment]
Closing this as I can't work on this, but I welcome contributions to improve this.
