### ISSUE TITLE
--help output to stderr on Windows

### ISSUE THREAD

**Issue by jack6th** [ncruces/zenity#88]
On windows
`zenity --help 2>&1 | findstr color`
It need '2>&1' to correctly get the help text about color. 
Most command line tools print --help or /? to the stdout.
It is unnatural.

**Comment by ncruces** [comment]
Sending help to stdout/err, and the return code of help, are a matter of opinion.
Go (which we use) sends to stderr, and returns non-zero.

Still my goal is to be compatible with zenity, where feasible, so fixed in 0d57bbbde85e16d9897c094a09376c7b23119cd7.
