### ISSUE TITLE
zenity 0.10.11 win32 cannot run on Windows 7

### ISSUE THREAD

**Issue by jack6th** [ncruces/zenity#90]
On Windows 7 0.10.10 works. 
0.10.11 'zenity --help' output
```Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        runtime/sys_windows_386.s:35 +0x25 fp=0x12fe68 sp=0x12fe64 pc=0x46c975

eax     0x8
ebx     0x6f2cec
ecx     0x0
edx     0x12fe90
edi     0x12fe6c
esi     0x12fec4
ebp     0x12fe6c
esp     0x12fe60
eip     0x0
eflags  0x10202
cs      0x1b
fs      0x3b
gs      0x0
```

**Comment by ncruces** [comment]
[Yes](https://go.dev/doc/go1.21#windows).

Feel free to build your own binaries with an older tool chain. I won't introduce incompatibilities on purpose, and may accept patches that keep compatibility with older Go versions.

That said, Windows 7 is out of support; Windows 10 was introduced 8 years ago.
