### ISSUE TITLE
Crystal wrapper

### ISSUE THREAD

**Issue by kojix2** [ncruces/zenity#96]
Hi @ncruces 

I made a very simple tool for Zenity with the Crystal language. (It just runs Zenity commands.)

https://github.com/kojix2/zenity.cr

Crystal is a new language. Windows support for Crystal just started. Calling C library functions from Crystal in Windows is not yet easy. Because of this, it's hard to use existing GUI frameworks.

In this situation, I think this tool, which makes dialog boxes easily on Windows, could be very helpful. Your work can help people using new languages like Crystal to make simple GUIs for Windows.

Please keep up the good work.
Thanks.

**Comment by ncruces** [comment]
Thanks! See the README now!
